export const investmentPlans = [
  {
    package: "premium plan",
    color1: "CF9B03",
    packageBenefit: [
      "99.5% AI accuracy",
      "24/7 Priority support",
      "Exclusive market insights",
      "Zero trading fees",
      "Dedicated account manager",
      "Customized portfolio",
      "VIP event invitations",
      "Early access to opportunities",
    ],
    image: "/assets/premiumm.png",
    min: 65000.0,
    max: 90000.0,
    minRoi: 162000.0,
    maxRoi: 220000.0,
  },
  {
    package: "gold plan",
    color1: "6B4BC9",
    packageBenefit: [
      "99% AI accuracy",
      "Extended support hours",
      "Premium market insights",
      "Reduced trading fees",
      "Personalized strategies",
      "Dedicated account manager",
      "Customized portfolio",
      "Flexible withdrawal options",
    ],
    image: "/assets/gold.png",
    min: 15000.0,
    max: 22000.0,
    minRoi: 63000.0,
    maxRoi: 82000.0,
  },
  {
    package: "silver plan",
    color1: "C0C0C0",
    packageBenefit: [
      "98% AI accuracy",
      "Advanced market insights",
      "Loyalty discounts",
      "Dedicated account manager",
      "Customized portfolio",
      "Weekly market analysis",
      "Investment community access",
      "Enhanced security",
    ],
    image: "/assets/silverr.png",
    min: 5000.0,
    max: 9000.0,
    minRoi: 47000.0,
    maxRoi: 56000.0,
  },
  {
    package: "bronze plan",
    color1: "CD7F32",
    packageBenefit: [
      "97% AI accuracy",
      "Live chat support",
      "Basic market insights",
      "Competitive fees",
      "Monthly market analysis",
      "Dedicated account manager",
      "Customized portfolio",
    ],
    image: "/assets/bronze.png",
    min: 1000.0,
    max: 3000.0,
    minRoi: 12000.0,
    maxRoi: 31000.0,
  },
];
